apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-dd8d8074.efs.us-west-2.amazonaws.com
    path: "/dev"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi