apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-stat350
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-3576799c.efs.us-west-2.amazonaws.com
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-stat350
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi