apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-stat218
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-9678773f.efs.us-west-2.amazonaws.com
    path: "/home"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-stat218
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi