kind: Pod
apiVersion: v1
metadata:
  name: test-pod3e
spec:
  containers:
  - name: test-pod
    image: nginx
    # image: gcr.io/google_containers/busybox:1.24
    # command:
    #   - "/bin/sh"
    # args:
    #   - "-c"
    #   - "touch /mnt/SUCCESS && exit 0 || exit 1"
  restartPolicy: "Never"
