kind: Pod
apiVersion: v1
metadata:
  name: test-pod3e
spec:
  containers:
  - name: test-pod
    image: nginx
    # image: gcr.io/google_containers/busybox:1.24
    # command:
    #   - "/bin/sh"
    # args:
    #   - "-c"
    #   - "touch /mnt/SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: pv-volume
        mountPath: /persistentvolumes
  volumes:
    - name: pv-volume
      nfs:
        server: fs-35e87e9c.efs.us-west-2.amazonaws.com 
        path: /
  restartPolicy: "Never"
